### ISSUE TITLE
Spam filter cleanup task can crash, how is it handled?

### ISSUE THREAD

**Issue by MythicManiac** [xiaoxiao921/CHEF#6]
https://github.com/xiaoxiao921/CHEF/blob/master/CHEF/Components/Watcher/Spam/SpamFilter.cs#L45

Here we're trusting that the db connection is successful. I'm not sure what happens with a scheduled task like that if it crashes, does it take down the entire application, or just the task in this case?

**Comment by xiaoxiao921** [comment]
A multitude of exceptions can actually happens when querying the DbContext but commands are all try catched by the discord net library and get logged.
In this case the current CleanUpTimerElapsed call will exit at that line if it can't retrieve the config and the exception will get logged in sentry.io / in the console. The app will resume normally

**Comment by MythicManiac** [comment]
Will the cleanup task be restarted if it fails like this?

**Comment by xiaoxiao921** [comment]
I just realized it will not restart if line 45 throw, since AutoReset is turned off and that the DbContext is not wrapped around the try catch with the finally scope that will schedule the next timer trigger. The method will stop at this line and `cleanUpTimer.Start();` won't be called. I also mistook this method for a discord bot command in my previous comment. Which make this method not in a try catch by its caller. Thanks for this, wouldn't have noticed otherwise

**Comment by MythicManiac** [comment]
Fix looks like it'd take care of it, thanks 👍
